## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/
git:
  depth: 99999999
matrix:
 allow_failures:
 - julia: nightly
after_success:
  - julia -e 'cd(Pkg.dir("StringBuilders")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
