name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.0.5, 1.2.0]
        julia-arch: [x64, x86]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia ${{ matrix.julia-version }}"
        uses: julia-actions/setup-julia@v0.1.0
        with:
          version: ${{ matrix.julia-version }}
      - name: Run tests
        uses: davidanthoff/julia-runtest@master
